<?php

/**
 * @file
 * Provides advanced recurring billing for licenses.
 */

/**
 * Implements hook_ctools_plugin_directory().
 */
function commerce_license_billing_ctools_plugin_directory($module, $plugin) {
  if ($module == 'commerce_license_billing') {
    return 'plugins/' . $plugin;
  }
}

/**
 * Implements hook_ctools_plugin_type().
 */
function commerce_license_billing_ctools_plugin_type() {
  $plugins['billing_cycle_engine'] = array(
    'classes' => array('class'),
  );

  return $plugins;
}

/**
 * Returns the available billing cycle engine plugins.
 */
function commerce_license_billing_cycle_engine_plugins() {
  ctools_include('plugins');
  $plugins = ctools_get_plugins('commerce_license_billing', 'billing_cycle_engine');
  foreach ($plugins as $key => $plugin) {
    if (!class_exists($plugin['class'])) {
      // Invalid class specified.
      unset($plugins[$key]);
      continue;
    }
  }
  uasort($plugins, 'ctools_plugin_sort');
  return $plugins;
}

/**
 * Implements hook_entity_info().
 */
function commerce_license_billing_entity_info() {
  // commerce_license_billing_cycle_type is too long for Drupal, so all
  // entity types and field names had to have their prefix shortened to cl_.
  // Yuck.
  $entity_info['cl_billing_cycle'] = array(
    'label' => t('Commerce License Billing Cycle'),
    'module' => 'commerce_license_billing',
    'base table' => 'cl_billing_cycle',
    'entity class' => 'CommerceLicenseBillingCycle',
    'controller class' => 'EntityAPIController',
    'label callback' => 'entity_class_label',
    'fieldable' => FALSE,
    'bundles' => array(),
    'bundle keys' => array(
      'bundle' => 'name',
    ),
    'entity keys' => array(
      'id' => 'billing_cycle_id',
      'bundle' => 'type',
    ),
  );
  // Bypass entity_load() as it cannot be used here (recursion).
  $billing_cycle_type = db_select('cl_billing_cycle_type', 'bct')
    ->fields('bct', array('name', 'title'))
    ->execute()
    ->fetchAllKeyed();
  foreach ($billing_cycle_type as $name => $title) {
    $entity_info['cl_billing_cycle']['bundles'][$name] = array(
      'label' => $title,
    );
  }

  $entity_info['cl_billing_cycle_type'] = array(
    'label' => t('Commerce License Billing Cycle Type'),
    'module' => 'commerce_license_billing',
    'base table' => 'cl_billing_cycle_type',
    'access callback' => 'commerce_license_billing_cycle_type_access',
    'controller class' => 'EntityBundlePluginEntityControllerExportable',
    'fieldable' => TRUE,
    'exportable' => TRUE,
    'bundles' => array(),
    'bundle of' => 'cl_billing_cycle',
    'bundle plugin' => array(
      'plugin type' => 'billing_cycle_engine',
    ),
    'entity keys' => array(
      'id' => 'billing_cycle_type_id',
      'bundle' => 'engine',
      'label' => 'title',
      'name' => 'name',
    ),
    'admin ui' => array(
      'path' => 'admin/commerce/config/license/billing-cycle-types',
      'file' => 'includes/commerce_license_billing.cycle_type_ui.inc',
      'controller class' => 'CommerceLicenseBillingCycleTypeUIController',
    ),
  );
  // Bypass entity_load() as it cannot be used here (recursion).
  foreach (commerce_license_billing_cycle_engine_plugins() as $name => $plugin) {
    $entity_info['cl_billing_cycle_type']['bundles'][$name] = array(
      'label' => $plugin['title'],
    );
  }

  return $entity_info;
}

/**
 * Implements hook_entity_info_alter().
 */
function commerce_license_billing_entity_info_alter(&$entity_info) {
  $entity_info['commerce_order']['bundles']['recurring'] = array(
    'label' => t('Recurring'),
  );
}

/**
 * Implements hook_commerce_line_item_type_info().
 */
function commerce_license_billing_commerce_line_item_type_info() {
  $line_item_types = array();
  $line_item_types['recurring'] = array(
    'type' => 'recurring',
    'name' => t('Recurring'),
    'description' => t('References a product in a recurring order.'),
    'product' => TRUE,
    'add_form_submit_value' => t('Add product'),
    'base' => 'commerce_product_line_item',
  );

  return $line_item_types;
}

/**
 * Access callback for the entity API.
 *
 * @param $op
 *   The operation being performed. One of 'view', 'update', 'create', 'delete'
 *   or just 'edit' (being the same as 'create' or 'update').
 * @param $cycle_type
 *   (optional) A cycle type to check access for. If nothing is given, access
 *   for all cycle types is determined.
 * @param $account
 *   (optional) The user to check for. Leave it to NULL to check for the global
 *   user.
 *
 * @return boolean
 *   Whether access is allowed or not.
 */
function commerce_license_billing_cycle_type_access($op, $cycle_type = NULL, $account = NULL) {
  $engines = commerce_license_billing_cycle_engine_plugins();
  return user_access('administer licenses', $account) && !empty($engines);
}

/**
 * Implements hook_flush_caches().
 */
function commerce_license_billing_flush_caches() {
  commerce_license_billing_configure_product_types();
  commerce_license_billing_configure_line_item_type();
  commerce_license_billing_configure_order_type();
}

/**
 * Creates recurring orders for licenses in the provided order.
 *
 * The provided order is first scanned, and all licensable products are
 * gathered. Their billing cycle types are gathered, and the appropriate
 * billing cyles are opened (if they haven't been previously).
 * An order per billing cycle is created (if it hasn't been previously),
 * and the new line items are added.
 *
 * @param $order
 *   The order to use as a base of the new recurring orders.
 */
function commerce_license_billing_create_recurring_orders($order) {
  // Group licenses by billing cycle type.
  $order_wrapper = entity_metadata_wrapper('commerce_order', $order);
  $billing_cycle_type_ids = array();
  $grouped_licenses = array();
  foreach ($order_wrapper->commerce_line_items as $line_item_wrapper) {
    if (!empty($line_item_wrapper->value()->commerce_license)) {
      $product_wrapper = $line_item_wrapper->commerce_product;
      if (!empty($product_wrapper->value()->cl_billing_cycle_type)) {
        $billing_cycle_type_id = $product_wrapper->cl_billing_cycle_type->raw();
        $billing_cycle_type_ids[] = $billing_cycle_type_id;
        $grouped_licenses[$billing_cycle_type_id][] = $line_item_wrapper->commerce_license->value();
      }
    }
  }
  // Load all found billing cycle types.
  $billing_cycle_types = entity_load('cl_billing_cycle_type', $billing_cycle_type_ids);

  foreach ($grouped_licenses as $billing_cycle_type_id => $licenses) {
    // Open a billing cycle.
    $billing_cycle_type = $billing_cycle_types[$billing_cycle_type_id];
    $billing_cycle = $billing_cycle_type->getBillingCycle($order->uid);
    // Sync the license timestamps with the billing cycle timestamps.
    foreach ($licenses as $license) {
      $license->granted = $billing_cycle->start;
      $license->expires = $billing_cycle->end;
      $license->save();
    }

    // Check if there's an existing order attached to that billing cycle.
    $query = new EntityFieldQuery();
    $query
      ->entityCondition('entity_type', 'commerce_order')
      ->entityCondition('bundle', 'recurring')
      ->propertyCondition('status', 'recurring_open')
      ->propertyCondition('uid', $order->uid)
      ->fieldCondition('cl_billing_cycle', 'target_id', $billing_cycle->billing_cycle_id);
    $results = $query->execute();
    if (!empty($results['commerce_order'])) {
      $recurring_order_id = key($results['commerce_order']);
      $recurring_order = commerce_order_load($recurring_order_id);
      $recurring_order_wrapper = entity_metadata_wrapper('commerce_order', $recurring_order);
      // Generate a base line item for each license.
      $existing_line_items = $recurring_order_wrapper->commerce_line_items->value();
      $line_items = array();
      foreach ($licenses as $license) {
        $line_items[] = commerce_license_billing_generate_base_line_item($license, $billing_cycle, $recurring_order_id);
      }
      $recurring_order_wrapper->commerce_line_items = array_merge($existing_line_items, $line_items);
      $recurring_order_wrapper->save();
    }
    else {
      commerce_license_billing_generate_recurring_order($order, $billing_cycle, $licenses);
    }
  }
}

/**
 * Generates a new recurring order.
 *
 * @param $previous_order
 *   The previous order.
 * @param $billing_cycle
 *   The billing cycle for the new order.
 * @param $licenses
 *   An array of licenses added to the new order.
 *
 * @return
 *   The newly created and saved recurring order.
 */
function commerce_license_billing_generate_recurring_order($previous_order, $billing_cycle, $licenses) {
  $previous_order_wrapper = entity_metadata_wrapper('commerce_order', $previous_order);
  // Create a new order and save it immediately to get the order_id.
  $recurring_order = commerce_order_new($previous_order->uid, 'recurring_open', 'recurring');
  commerce_order_save($recurring_order);

  $recurring_order_wrapper = entity_metadata_wrapper('commerce_order', $recurring_order);
  $recurring_order_wrapper->commerce_customer_billing = $previous_order_wrapper->commerce_customer_billing->value();
  $recurring_order_wrapper->cl_billing_cycle = $billing_cycle;
  // Generate a base line item for each license.
  // If this is the first recurring order, licenses of all statuses are taken,
  // since they haven't been activated yet. However, if the previous order was
  // also recurring, only active licenses are taken since the revoked / expired
  // ones have already been charged for.
  $active_only = ($previous_order->type == 'recurring');
  $line_items = array();
  foreach ($licenses as $license) {
    if ($active_only && $license->status != COMMERCE_LICENSE_ACTIVE) {
      continue;
    }
    $line_items[] = commerce_license_billing_generate_base_line_item($license, $billing_cycle, $recurring_order->order_id);
  }
  $recurring_order_wrapper->commerce_line_items = $line_items;
  $recurring_order_wrapper->save();

  return $recurring_order;
}

/**
 * Generates the recurring line item for the base product of a license.
 *
 * Takes into account whether the product is prepaid or postpaid.
 *
 * @param $license
 *   The license entity.
 * @param $billing_cycle
 *   The billing cycle entity.
 * @param $order_id
 *   The order_id to be set on the newly created line items.
 *
 * @return
 *   The newly created and saved line item.
 */
function commerce_license_billing_generate_base_line_item($license, $billing_cycle, $order_id) {
  $product_wrapper = $license->wrapper->product;
  // Charge for the base product, there's no usage at this point.
  $line_item = commerce_line_item_new('recurring', $order_id);
  $line_item_wrapper = entity_metadata_wrapper('commerce_line_item', $line_item);
  $line_item_wrapper->line_item_label = $product_wrapper->title->value();
  $line_item_wrapper->commerce_product = $product_wrapper->value();
  $line_item_wrapper->quantity = 1;
  $line_item_wrapper->cl_billing_license = $license;

  $line_item_wrapper->commerce_unit_price = $license->wrapper->product->commerce_price->value();
  if ($product_wrapper->cl_billing_type->value() == 'prepaid') {
    // In case of prepaid, the line item always charges for the next
    // billing cycle. So if the just opened billing cycle is "February",
    // the line item needs to charge for March.
    $billing_cycle_type = entity_load_single('cl_billing_cycle_type', $billing_cycle->type);
    $next_billing_cycle = $billing_cycle_type->getNextBillingCycle($billing_cycle, FALSE);
    $line_item_wrapper->cl_billing_start = $next_billing_cycle->start;
    $line_item_wrapper->cl_billing_end = $next_billing_cycle->end;
  }
  elseif ($product_wrapper->cl_billing_type->value() == 'postpaid') {
    // In case of postpaid, the line item always charges for the current
    // billing cycle.
    $line_item_wrapper->cl_billing_start = $billing_cycle->start;
    $line_item_wrapper->cl_billing_end = $billing_cycle->end;
  }
  // Trigger price calculation to get any needed discounts or price changes.
  rules_invoke_event('commerce_product_calculate_sell_price', $line_item);
  // Save the line item.
  $line_item_wrapper->save();

  return $line_item_wrapper->value();
}

/**
 * Estimate the cost of a license with the given plan and usage.
 *
 * @param $license_type
 *   The license type.
 * @param $product
 *   The product representing the license plan.
 * @param $usage
 *  An array in the usage_group => quantity format.
 *
 * @return
 *   An array with the following keys:
 *   - billing_cycle: An array with the title, start, end keys.
 *   - charges: An array of arrays with product, unit_price, quantity keys.
 *   - total: The total price array (amount, currency_code, data).
 */
function commerce_license_billing_estimate_cost($license_type, $product, $usage = NULL) {
  // Prepare commonly needed data.
  $product_wrapper = entity_metadata_wrapper('commerce_product', $product);
  $zero_price = array(
    'amount' => 0,
    'currency_code' => $product_wrapper->commerce_price->currency_code->value(),
    'data' => array(),
  );
  $zero_price['data'] = commerce_price_component_add($zero_price, 'base_price', $zero_price, TRUE, FALSE);
  // Construct a billing cycle.
  $billing_cycle_type = $product_wrapper->cl_billing_cycle_type->value();
  $billing_cycle = $billing_cycle_type->getBillingCycle($GLOBALS['user']->uid, REQUEST_TIME, FALSE);

  $estimation = array(
    'billing_cycle' => array(
      'title' => $billing_cycle->label(),
      'start' => $billing_cycle->start,
      'end' => $billing_cycle->end,
    ),
  );
  // Price the base product.
  $price = commerce_license_billing_calculate_sell_price($product, 1, $billing_cycle);
  $estimation['charges'][] = array(
    'product' => $product,
    'quantity' => 1,
    'unit_price' => $price,
    'total' => $price,
  );
  // Price the usage.
  $license = entity_create('commerce_license', array('type' => $license_type));
  $license->product_id = $product->product_id;
  $license->granted = $billing_cycle->start;
  $license->expires = $billing_cycle->end;
  if ($license instanceof CommerceLicenseBillingUsageInterface && !empty($usage)) {
    $usage_groups = $license->usageGroups();
    foreach ($usage as $group_name => $quantity) {
      $usage_group = $usage_groups[$group_name];
      $usage_product = commerce_product_load_by_sku($usage_group['product']);
      if ($quantity <= $usage_group['free_quantity']) {
        $unit_price = $total_price = $zero_price;
      }
      else {
        $quantity -= $usage_group['free_quantity'];
        $unit_price = commerce_license_billing_calculate_sell_price($usage_product, $quantity, $billing_cycle);
        $total_price = $unit_price;
        // Multiply the amount and all price components by quantity.
        $total_price['amount'] *= $quantity;
        foreach ($total_price['data']['components'] as $key => &$component) {
          $component['price']['amount'] *= $quantity;
        }
      }

      $estimation['charges'][] = array(
        'product' => $usage_product,
        'quantity' => $quantity,
        'unit_price' => $unit_price,
        'total' => $total_price,
      );
    }
  }
  // Calculate the total.
  $estimation['total'] = $zero_price;

  foreach ($estimation['charges'] as $charge) {
    // Add the charge total to the estimation total.
    $estimation['total']['amount'] += $charge['total']['amount'];
    $estimation['total']['data'] = commerce_price_components_combine($estimation['total'], $charge['total']);
  }
  // Make sure the final amount has been rounded.
  $estimation['total']['amount'] = round($estimation['total']['amount']);

  return $estimation;
}

/**
 * Returns the calculated sell price for the given product.
 *
 * @param $product
 *   The product whose sell price will be calculated.
 * @param $quantity
 *   The product quantity.
 * @param $billing_cycle
 *   The billing cycle for this product.
 *
 * @return
 *   A price field data array as returned by entity_metadata_wrapper().
 */
function commerce_license_billing_calculate_sell_price($product, $quantity, $billing_cycle) {
  $line_item = commerce_line_item_new('recurring');
  $line_item_wrapper = entity_metadata_wrapper('commerce_line_item', $line_item);
  $line_item_wrapper->cl_billing_start = $billing_cycle->start;
  $line_item_wrapper->cl_billing_end = $billing_cycle->end;
  $line_item_wrapper->quantity = $quantity;
  commerce_product_line_item_populate($line_item, $product);
  // Pass the line item to Rules.
  rules_invoke_event('commerce_product_calculate_sell_price', $line_item);
  // Get the calculated unit price. If it was unset, provide a default.
  $unit_price = $line_item_wrapper->commerce_unit_price->value();
  if (empty($unit_price)) {
    $unit_price = commerce_price_field_data_auto_creation();
  }

  return $unit_price;
}

/**
 * Returns the billing cycle for the given license.
 *
 * @param $license
 *   The license entity.
 *
 * @return
 *   A billing cycle entity, or FALSE if none found.
 */
function commerce_license_billing_get_license_billing_cycle($license) {
  // Load a line item that references the license.
  $query = new EntityFieldQuery;
  $query
    ->entityCondition('entity_type', 'commerce_line_item')
    ->entityCondition('bundle', 'recurring')
    ->fieldCondition('cl_billing_license', 'target_id', $license->license_id)
    ->range(0, 1);
  $result = $query->execute();
  if ($result) {
    $line_item_id = key($result['commerce_line_item']);
    $line_item = commerce_line_item_load($line_item_id);
    $line_item_wrapper = entity_metadata_wrapper('commerce_line_item', $line_item);
    return $line_item_wrapper->order->cl_billing_cycle->value();
  }
  else {
    return FALSE;
  }
}

/**
 * Implements hook_commerce_license_presave().
 *
 * Ensures that a new license revision is created on product or status changes.
 */
function commerce_license_billing_commerce_license_presave($license) {
  if (empty($license->original) || $license->status < COMMERCE_LICENSE_ACTIVE) {
    // The license is new, or hasn't been activated yet.
    return;
  }

  $product_changed = ($license->product_id != $license->original->product_id);
  $status_changed = ($license->status != $license->original->status);
  if ($product_changed || $status_changed) {
    $license->is_new_revision = TRUE;
  }
}

/**
 * Changes the license plan.
 *
 * @todo
 * Allow the plan change to be queued until the end of the cycle, and do it
 * by default for prepaid cycles.
 *
 * @param $license
 *   The license entity.
 * @param $product_id
 *   The product_id of the new plan.
 */
function commerce_license_billing_change_plan($license, $product_id) {
  if ($license->wrapper->product->cl_billing_type->value() == 'prepaid') {
    // We don't support changing plans for prepaid products for now.
    return;
  }

  // Change the plan, and trigger a synchronization.
  $license->product_id = $product_id;
  $license->save();
  if ($license instanceof CommerceLicenseSynchronizableInterface) {
    commerce_license_enqueue_sync($license);
  }
}

/**
 * Returns the license plan history for an open billing cycle.
 *
 * @param $license
 *   The license entity.
 * @param $billing_cycle
 *   The billing cycle entity.
 *
 * @return
 *   An array of history records in the following format:
 *   - revision_id: The revision_id of the history record.
 *   - product_id: The id of the product representing the plan.
 *   - start: The start timestamp.
 *   - end: The end timestamp.
 */
function commerce_license_billing_plan_history_list($license, $billing_cycle) {
  $history = &drupal_static(__FUNCTION__, array());
  if (!isset($history[$license->license_id])) {
    // Fetch revisions that started or ended in this billing cycle, or are still
    // in progress.
    $cycle_duration = array($billing_cycle->start, $billing_cycle->end);
    $or = db_or();
    $or->condition('revision_created', $cycle_duration, 'BETWEEN');
    $or->condition('revision_ended', $cycle_duration, 'BETWEEN');
    $or->condition('revision_ended', 0);

    $query = db_select('commerce_license_revision', 'clr');
    $query->addField('clr', 'revision_id');
    $query->addField('clr', 'product_id');
    $query->addField('clr', 'status');
    $query->addField('clr', 'revision_created', 'start');
    $query->addField('clr', 'revision_ended', 'end');
    $query->condition('license_id', $license->license_id);
    $query->condition('status', COMMERCE_LICENSE_ACTIVE);
    $query->condition($or);
    $license_history = $query->execute()->fetchAll(PDO::FETCH_ASSOC);

    // Merge any records with the same product_id and status that are right
    // next to each other (edge case when a revision wasn't created for a
    // product_id or status change, but for another purpose).
    $previous_index = NULL;
    foreach ($license_history as $index => $history_record) {
      if (!isset($previous_index)) {
        $previous_index = $index;
        continue;
      }

      $previous_record = $license_history[$previous_index];
      $products_match = ($history_record['product_id'] == $previous_record['product_id']);
      $statuses_match = ($history_record['status'] == $previous_record['status']);
      $times_match = ($history_record['start'] - $previous_record['end'] === 1);
      if ($products_match && $statuses_match && $times_match) {
        $license_history[$previous_index]['end'] = $history_record['end'];
        unset($license_history[$index]);
        continue;
      }
      $previous_index = $index;
    }

    // Adjust the start and end timestamps for the current billing cycle.
    foreach ($license_history as &$history_record) {
      if ($history_record['start'] < $billing_cycle->start) {
        $history_record['start'] = $billing_cycle->start;
      }
      if (empty($history_record['end'])) {
        $history_record['end'] = $billing_cycle->end;
      }
    }

    // Add the data to the static cache.
    $history[$license->license_id] = $license_history;
  }

  return $history[$license->license_id];
}

/**
 * Adds a usage record for the specified license and usage group.
 *
 * @param $license
 *   The license entity.
 * @param $group
 *   The usage group, as defined by $license->usageGroups().
 * @param $quantity
 *   The usage quantity.
 * @param $start
 *   The unix timestamp when usage started. Optional if the usage group
 *   specified "immediate" => TRUE, otherwise required.
 * @param $end
 *   The unix timestamp when usage ended. Optional if the usage group
 *   specified "immediate" => TRUE, otherwise required.
 */
function commerce_license_billing_usage_add($license, $group, $quantity, $start = NULL, $end = NULL) {
  $usage_groups = $license->usageGroups();
  if (!isset($usage_groups[$group])) {
    throw new Exception('Invalid usage group specified for commerce_license_billing_usage_add().');
  }
  $usage_group = $usage_groups[$group];
  if (empty($usage_group['immediate']) && (!$start || !$end)) {
    throw new Exception('Empty $start or $end timestamps in commerce_license_billing_usage_add().');
  }
  // If usage reporting for this group is immediate, it is safe to initialize
  // $start to current time.
  if (!empty($usage_group['immediate']) && !$start) {
    $start = REQUEST_TIME;
  }

  // If a gauge just changed, close the previous usage record.
  if ($usage_group['type'] == 'gauge' && !empty($usage_group['immediate'])) {
    $previous_end = $start - 1;
    db_update('cl_billing_usage')
      ->fields(array(
        'end' => $previous_end,
      ))
      ->condition('license_id', $license->license_id)
      ->condition('usage_group', $group)
      ->condition('end', 0)
      ->execute();
  }

  db_insert('cl_billing_usage')
    ->fields(array(
      'license_id' => $license->license_id,
      'usage_group' => $group,
      'quantity' => $quantity,
      'start' => $start,
      'end' => (int) $end,
    ))
    ->execute();
}

/**
 * Clears closed usage records for the provided license and usage group.
 *
 * @param  $license
 *   The license entity.
 * @param $group
 *   (Optional) The usage group, as defined by $license->usageGroups().
 */
function commerce_license_billing_usage_clear($license, $group = NULL) {
  $delete = db_delete('cl_billing_usage');
  $delete->condition('license_id', $license->license_id);
  $delete->condition('end', 0, '!=');
  if ($group) {
    $delete->condition('usage_group', $group);
  }
  $delete->execute();
}

/**
 * Returns the current usage for the provided license and usage group.
 *
 * If the usage group is of type 'counter', the total usage is returned.
 * If the usage group is of type 'gauge', the last reported usage is returned.
 *
 * @param  $license
 *   The license entity.
 * @param $group
 *   The usage group, as defined by $license->usageGroups().
 *
 * @return
 *   The numeric usage amount.
 */
function commerce_license_billing_current_usage($license, $group) {
  $usage_groups = $license->usageGroups();
  if (!isset($usage_groups[$group])) {
    throw new Exception('Invalid usage group specified for commerce_license_billing_current_usage().');
  }
  $usage_group = $usage_groups[$group];

  $data = array(
    ':license_id' => $license->license_id,
    ':group' => $group,
  );
  if ($usage_group['type'] == 'counter') {
    $usage = db_query("SELECT SUM(quantity) FROM {cl_billing_usage}
                    WHERE license_id = :license_id AND usage_group = :group
                      GROUP BY license_id, usage_group", $data)->fetchColumn();
  }
  elseif ($usage_group['type'] == 'gauge') {
    $usage = db_query("SELECT quantity FROM {cl_billing_usage}
                    WHERE license_id = :license_id AND usage_group = :group
                      ORDER BY start DESC LIMIT 1", $data)->fetchColumn();
  }

  return (int) $usage;
}

/**
 * Returns the license usage history for an open billing cycle.
 *
 * @param  $license
 *   The license entity.
 * @param $billing_cycle
 *   The billing cycle entity.
 *
 * @return
 *   An array of usage records in the following format:
 *   - product_id: The id of the product representing the plan.
 *   - start: The start timestamp.
 *   - end: The end timestamp.
 */
function commerce_license_billing_usage_history_list($license, $billing_cycle) {
  $history = &drupal_static(__FUNCTION__, array());
  if (empty($history[$license->license_id])) {
    $query = db_select('cl_billing_usage', 'bu');
    $query
      ->fields('bu', array('usage_group', 'quantity', 'start', 'end'))
      ->condition('license_id', $license->license_id)
      ->orderBy('start', 'ASC');
    $usage_history = $query->execute()->fetchAll(PDO::FETCH_ASSOC);
    // Adjust the start and end timestamps for the current billing cycle.
    foreach ($usage_history as $index => &$usage_record) {
      if ($usage_record['start'] < $billing_cycle->start) {
        $usage_record['start'] = $billing_cycle->start;
      }
      if (empty($usage_record['end'])) {
        $usage_record['end'] = $billing_cycle->end;
      }
    }

    $history[$license->license_id] = $usage_history;
  }

  return $history[$license->license_id];
}

/**
 * Ensures that the license product types have the required billing fields.
 *
 * Fields:
 * - cl_billing_cycle_type: an entityreference field pointing to the
 *   billing cycle type.
 * - cl_billing_type: an options field for selecting prepaid or postpaid.
 */
function commerce_license_billing_configure_product_types() {
  $field = field_info_field('cl_billing_cycle_type');
  if (empty($field)) {
    $field = array(
      'field_name' => 'cl_billing_cycle_type',
      'type' => 'entityreference',
      'cardinality' => 1,
      'translatable' => 0,
      'module' => 'entityreference',
      'settings' => array(
        'target_type' => 'cl_billing_cycle_type',
        'handler' => 'base',
      ),
    );
    field_create_field($field);
  }
  foreach (commerce_license_product_types() as $type_name) {
    $instance = field_info_instance('commerce_product', 'cl_billing_cycle_type', $type_name);
    if (empty($instance)) {
      $license_type_instance = field_info_instance('commerce_product', 'commerce_license_type', $type_name);
      $instance = array(
        'field_name' => 'cl_billing_cycle_type',
        'entity_type' => 'commerce_product',
        'bundle' => $type_name,
        'label' => 'License billing cycle type',
        'required' => FALSE,
        'widget' => array(
          'type' => 'options_select',
          'module' => 'options',
          // Make sure that this field is shown right after the license type.
          'weight' => $license_type_instance['widget']['weight'] + 1,
        ),
      );
      field_create_instance($instance);
    }
  }

  $field = field_info_field('cl_billing_type');
  if (empty($field)) {
    $field = array(
      'field_name' => 'cl_billing_type',
      'type' => 'list_text',
      'entity_type' => 'commerce_product',
      'cardinality' => 1,
      'translatable' => 0,
      'module' => 'list',
      'settings' => array(
        'allowed_values' => array(
          'prepaid' => 'Prepaid',
          'postpaid' => 'Postpaid'
        ),
      ),
    );
    field_create_field($field);
  }
  foreach (commerce_license_product_types() as $type_name) {
    $instance = field_info_instance('commerce_product', 'cl_billing_type', $type_name);
    if (empty($instance)) {
      $license_type_instance = field_info_instance('commerce_product', 'commerce_license_type', $type_name);
      $instance = array(
        'field_name' => 'cl_billing_type',
        'entity_type' => 'commerce_product',
        'bundle' => $type_name,
        'label' => 'License billing type',
        'required' => TRUE,
        'widget' => array(
          'type' => 'options_buttons',
          'module' => 'options',
          // Make sure that this field is shown right after the billing cycle type.
          'weight' => $license_type_instance['widget']['weight'] + 1,
        ),
      );
      field_create_instance($instance);
    }
  }
}

/**
 * Ensures that the recurring line item type has the required fields.
 *
 * Fields:
 * - cl_billing_start: a datetime field.
 * - cl_billing_end: a datetime field.
 * - cl_billing_license: an entityreference field pointing to the license
 *   for which the line item was generated.
 */
function commerce_license_billing_configure_line_item_type() {
  if (!$line_item_type = commerce_line_item_type_load('recurring')) {
    return;
  }
  // Make sure Commerce has created all of its required fields.
  commerce_line_item_configure_line_item_type($line_item_type);

  $field = field_info_field('cl_billing_start');
  if (empty($field)) {
    $field = array(
      'field_name' => 'cl_billing_start',
      'type' => 'datetime',
      'cardinality' => 1,
      'translatable' => 0,
      'module' => 'date',
    );
    field_create_field($field);
  }
  $instance = field_info_instance('commerce_line_item', 'cl_billing_start', 'recurring');
  if (empty($instance)) {
    $instance = array(
      'field_name' => 'cl_billing_start',
      'entity_type' => 'commerce_line_item',
      'bundle' => 'recurring',
      'label' => 'Billing cycle start',
      'required' => TRUE,
      'widget' => array(
        'type' => 'date_select',
        'module' => 'date',
      ),
    );
    field_create_instance($instance);
  }

  $field = field_info_field('cl_billing_end');
  if (empty($field)) {
    $field = array(
      'field_name' => 'cl_billing_end',
      'type' => 'datetime',
      'cardinality' => 1,
      'translatable' => 0,
      'module' => 'date',
    );
    field_create_field($field);
  }
  $instance = field_info_instance('commerce_line_item', 'cl_billing_end', 'recurring');
  if (empty($instance)) {
    $instance = array(
      'field_name' => 'cl_billing_end',
      'entity_type' => 'commerce_line_item',
      'bundle' => 'recurring',
      'label' => 'Billing cycle end',
      'required' => TRUE,
      'widget' => array(
        'type' => 'date_select',
        'module' => 'date',
      ),
    );
    field_create_instance($instance);
  }

  $field = field_info_field('cl_billing_license');
  if (!$field) {
    $field = array(
      'settings' => array(
        'handler' => 'base',
        'target_type' => 'commerce_license',
      ),
      'field_name' => 'cl_billing_license',
      'type' => 'entityreference',
    );
    field_create_field($field);
  }
  $instance = field_info_instance('commerce_line_item', 'cl_billing_license', 'recurring');
  if (empty($instance)) {
    $instance = array(
      'field_name' => 'cl_billing_license',
      'entity_type' => 'commerce_line_item',
      'bundle' => 'recurring',
      'label' => 'License',
      'required' => TRUE,
    );

    field_create_instance($instance);
  }
}

/**
 * Ensures that the recurring order type has the required fields.
 *
 * Fields:
 * - cl_billing_cycle: an entityreference field pointing to a
 *   billing cycle.
 */
function commerce_license_billing_configure_order_type() {
  // Make sure Commerce has created all of its required fields.
  commerce_order_configure_order_type('recurring');

  $field = field_info_field('cl_billing_cycle');
  if (empty($field)) {
    $field = array(
      'field_name' => 'cl_billing_cycle',
      'type' => 'entityreference',
      'cardinality' => 1,
      'translatable' => 0,
      'module' => 'entityreference',
      'settings' => array(
        'target_type' => 'cl_billing_cycle',
        'handler' => 'base',
      ),
    );
    field_create_field($field);
  }
  $instance = field_info_instance('commerce_order', 'cl_billing_cycle', 'recurring');
  if (empty($instance)) {
    $instance = array(
      'field_name' => 'cl_billing_cycle',
      'entity_type' => 'commerce_order',
      'bundle' => 'recurring',
      'label' => 'Billing cycle',
      'required' => TRUE,
      'widget' => array(
        'type' => 'options_select',
        'module' => 'options',
      ),
    );
    field_create_instance($instance);
  }
}

/**
 * Implements hook_theme().
 */
function commerce_license_billing_theme() {
  return array(
    'commerce_license_billing_estimate' => array(
      'variables' => array(
        'estimation' => NULL,
      ),
      'file' => 'theme/commerce_license_billing.theme.inc',
    ),
  );
}

