<?php

/**
 * @file
 * Provides example license types for testing billing.
 */

/**
 * Implements hook_ctools_plugin_directory().
 */
function commerce_license_billing_test_ctools_plugin_directory($owner, $plugin_type) {
  if (in_array($owner, array('commerce_license', 'commerce_license_billing'))) {
    return "plugins/$plugin_type";
  }
}

/**
 * Implements hook_commerce_license_billing_initial_usage().
 */
function commerce_license_billing_test_commerce_license_billing_initial_usage($license, $group_name) {
  if ($group_name == 'environments') {
    return 2;
  }
}
